---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-app-mesh-inject-sa
  namespace: appmesh-inject
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-app-mesh-inject-cr
rules:
  - apiGroups: ["*"]
    resources: ["replicasets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-app-mesh-inject-binding
subjects:
  - kind: ServiceAccount
    name: aws-app-mesh-inject-sa
    namespace: appmesh-inject
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: aws-app-mesh-inject-cr
  apiGroup: ""
---
apiVersion: v1
kind: Service
metadata:
  name: aws-app-mesh-inject
  namespace: appmesh-inject
  labels:
    name: aws-app-mesh-inject
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: aws-app-mesh-inject
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-app-mesh-inject
  namespace: appmesh-inject
  labels:
    name: aws-app-mesh-inject
spec:
  replicas: 1
  template:
    metadata:
      name: aws-app-mesh-inject
      labels:
        name: aws-app-mesh-inject
    spec:
      serviceAccountName: aws-app-mesh-inject-sa
      containers:
        - name: webhook
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-app-mesh-inject:v0.1.3
          env:
            - name: APPMESH_REGION
              value: 
            - name: APPMESH_NAME
              value: dj-app
            - name: APPMESH_LOG_LEVEL
              value: debug
            - name: ENABLE_ENVOY_XRAY_TRACING
              value: "true"
            - name: ENABLE_ENVOY_STATS_TAGS
              value: "true"
          imagePullPolicy: Always
          command:
            - ./appmeshinject
            - -sidecar-image=111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.9.0.0-prod
            - -init-image=111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:latest
            - -inject-xray-sidecar=true
          resources:
            limits:
              memory: 500Mi
              cpu: 300m
            requests:
              memory: 500Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: aws-app-mesh-inject
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-app-mesh-inject
webhooks:
  - name: aws-app-mesh-inject.aws.amazon.com
    clientConfig:
      service:
        name: aws-app-mesh-inject
        namespace: appmesh-inject
        path: "/"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1Ea3lPVEE0TVRVek4xb1hEVEk1TURreU5qQTRNVFV6TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWYyCmQ1OHVncTlycDJENTJNZmFreXY1U0lRUjgzZGpMUXVEeWtkdjliNmlyblhzc1BQSXNOdVVzM2RxYXRJbk9vM2cKZnhNUDNpQW1zVkQyVHRwTEFKREd1dDhOWEZ6d3JNdGVmeHFqK0ZXTDF5Q1lKUFZqUFFXMkpMcW5LeHFlMm9xSQpyTHpUM0prbVorT2NBTjJiclpHRy9qVUtqTGJ2S2d4Z2ZobjR3THNPRUJPT3RnWkh2Q3VJUkdJbnBCY0E2YjRLCnVzSHFRdTNQT2Erb3hCcUM2VzlBWDJjM01ibHppblRLQVpDZ3d3SkF0UXRXUGZhNGQvZnZkMUZCa2ZRMDQ2MXcKYnFISHZ0SDZ0TUY3NXdaOWk3NUdLdGt6SjJ4Z2ZuVnNUaTdoT2dZRUtpaG44TEhjYkdqbVdpUGlUclEvTzNaNwovQ0pqcmNBcXBuQ09ySWw0cW1VQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCbVVEZ2tlcDByZ29ybGdySjJvRHZrcHVhQ1EKS29ldDR4c1p4Nm1oRnF6RVBmUVNFbCttNVlGc005cEllMTJEU2hSZkJFN2VDdEp6R1ZteHduRlhHNm9pNlJWWQp0QzVzQmUxSE13NXlBTTR4WUVzMGFxeTl2WDFqS1ZjaDQ4OGRjaEIzNHBpVy93WkdNVDcvNHRxOHJwVzcwejZmCm9VOEVVSm1GajU5c2hYT0RuWjlFeXNBLzdSRkxRQnhJR3grQVk1WStwSzVXMWhPaHhieE0vMnl6b3JCWlJiK2sKbm9hOElsRkhxcHFhQVd4a3NOeDlHeTN1NFdwK1M5TXBuNTZ4cGlISU1UMG9LM1RUY3NtVlB1N3ZMcElPYVNjYQp2SFZpdk8zSTBZSFI5QVFsQ0VhQnFBeVg2U1hDVHVrODY2amt5RzV5aWVxN1Fjcy9MVmlVMWMzNkJucz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        appmesh.k8s.aws/sidecarInjectorWebhook: enabled
