---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-app-mesh-inject-sa
  namespace: appmesh-inject
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-app-mesh-inject-cr
rules:
  - apiGroups: ["*"]
    resources: ["replicasets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-app-mesh-inject-binding
subjects:
  - kind: ServiceAccount
    name: aws-app-mesh-inject-sa
    namespace: appmesh-inject
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: aws-app-mesh-inject-cr
  apiGroup: ""
---
apiVersion: v1
kind: Service
metadata:
  name: aws-app-mesh-inject
  namespace: appmesh-inject
  labels:
    name: aws-app-mesh-inject
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: aws-app-mesh-inject
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-app-mesh-inject
  namespace: appmesh-inject
  labels:
    name: aws-app-mesh-inject
spec:
  replicas: 1
  template:
    metadata:
      name: aws-app-mesh-inject
      labels:
        name: aws-app-mesh-inject
    spec:
      serviceAccountName: aws-app-mesh-inject-sa
      containers:
        - name: webhook
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-app-mesh-inject:v0.1.3
          env:
            - name: APPMESH_REGION
              value: 
            - name: APPMESH_NAME
              value: dj-app
            - name: APPMESH_LOG_LEVEL
              value: debug
            - name: ENABLE_ENVOY_XRAY_TRACING
              value: "true"
            - name: ENABLE_ENVOY_STATS_TAGS
              value: "true"
          imagePullPolicy: Always
          command:
            - ./appmeshinject
            - -sidecar-image=111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.9.0.0-prod
            - -init-image=111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:latest
            - -inject-xray-sidecar=true
          resources:
            limits:
              memory: 500Mi
              cpu: 300m
            requests:
              memory: 500Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: aws-app-mesh-inject
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-app-mesh-inject
webhooks:
  - name: aws-app-mesh-inject.aws.amazon.com
    clientConfig:
      service:
        name: aws-app-mesh-inject
        namespace: appmesh-inject
        path: "/"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXpNREU0TlRFMU4xb1hEVEk1TVRBeU56RTROVEUxTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmVXClUyS1RKcUI1TnNzZjFqd2taWXUvNXNWbi9nYUs4UWd0ZE5DTmFiNlc1U29Qck9nemxGTXE1SXdvZWVlUXV0c1cKL1U1NDhQVSs5MnN3ajFmckxkUzllZCt4ZlkrUEJTU2l4M3NuUHhyUlJCY1FldkFxWlhZZjJnRVp4RGtIbWZ6RgpBRHcycjRPbTVqaVV5SDh2VlpranpTTk0wdzBmUDh4M1lvdmg0RHZreE9QNjBKcHdjWVJOVkxyM3ZTQTdLQmdzCnVmWHV2Y3YwTmxsNnZSS3JhVFp5ZVk3UkxnOHFXWmRFS1o3aElYSXNmR3lDZzhONjA3UWh2Y0E1WHdscDROWDUKdlgyVEg4T2NjZlU1VEc0ZVdoekFvNWZpUmtmbm1pejExejZnSE5XREFJV20ybGxOMEk5QjRyM3IwZlBtV2ZsYwpFWkpMeUVseFhITERKWkMyZnVNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIUmJyYVBiS0w2MXdCZTlscUZtWmk0R3ZMOHAKakRXRHVrcFRCQk9acG5GUU42SWY2MTVJakp2QlhZSVYyTnVKdU1HWUlkRk1qK1dwQm1Sai91eHJiNWRCZFR5RwpqdWJFTUZ0YlZvT01hVmx5ZTlMcmErVHZUOXd2VDl5SWt0b0VSYWJseEU0S09SZGZjZjJqVnFYaDA1WjRLQ1QzClF2aE4wcWcrR3RSOFRuYTJRYjM0K280T2M5VU40bEFuenRieTVFZmd1Vms5RHFFeW9mck9OQUNHYTJyc3I5akkKREtjSHc1aXpiWDZveDlGYjJ1VFI2dmRrekZIQTJXM0g0R0dLYWFJczZ6ejhDNTA1VCtKM0ZhVDcwYk1YVE11QwpBYzhZdFgwa2ZJMW8wTVA3N3dwVlJLOHR6SHJyeHRnSDN0TVVaWWJaSHZtUzRQMUFIOGtISTlEU29uVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        appmesh.k8s.aws/sidecarInjectorWebhook: enabled
